# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-06 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.FloatField(default=100.0)),
            ],
        ),
        migrations.CreateModel(
            name='MenuSubtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_quantified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MenuType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'SERVED'), (3, 'PAID')], default=1)),
                ('ordernum', models.SmallIntegerField()),
                ('total', models.FloatField()),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='menu.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(1, 'PENDING'), (2, 'SERVED'), (3, 'PAID')], default=1)),
                ('price', models.FloatField()),
                ('menuitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='menu.MenuItem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='menu.Order')),
            ],
        ),
        migrations.AddField(
            model_name='menusubtype',
            name='menutype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menusubtypes', to='menu.MenuType'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menusubtype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menuitems', to='menu.MenuSubtype'),
        ),
    ]
